package-lock.json, package.json, src/utils/guid.js
`Math.random` is not a secure or entropically sufficient source for generating GUIDs, replace with `nanoid` like in the core surrealdb repository.
=> 0.1.1 - replace Math.random with nanoid

src/index.js
Event listeners — including the one handling the `close` cleanup — were being removed before the ws connection was closed.
Resolves #6
=> Remove `removeAllListeners` call before close

test/e2e/scripts/run-e2e.sh
run-e2e.sh is currently failing because the build step is incorrect
Before:
```sh
npm run build &&
```
After:
```sh
deno task build &&
```
I'm guessing the broken step once relied on a package.json script command that no longer exists.
=> fix: e2e build step

src/index.ts
Currently, the helper functions simply return either a single item or an array of items.
This PR is not optimal, but the best way to handle this as far as I can see.
Essentially, when you define a variable: 
```typescript
const userId = 'user:tobie';
```
Then typescript is smart enough to be able to compare it against a type like: 
```typescript
type Thing = `${string}:${string}`;
// Hint: The type is true :)
type userIdIsThing = 
(typeof userId) extends Thing ? true : false; 
```
<hr />
```typescript
import { Surreal, Thing } from 'surrealdb.js';
const surreal: Surreal;
type User = {
id: Thing;
name: string;
};
// Returns type "User[]" (as a promise)
const result = await surreal.select<User>('user');
// Returns type "User" (as a promise)
const result = await …
```
=> Return single item or item[] based on thing

src/library/SurrealSocket.ts
Currently, the queue will hog up, slowly eating memory. As a message comes back only once (outside of live queries, will be separate queue), it can't hurt to clean it up when a message is processed
=> Cleanup queue after message is processed

compile.ts, src/library/WebSocket/node.ts
Issues arrised with nextjs server components importing the `isomorphic-ws` package, which has some fundamental problems and is not maintained.
`unws` is an alternative package that provides solutions to issues `isomorphic-ws` has.
=> Replace isomorphic-ws with unws

project.json
_Doing a minor bugfix release to unblock some people, there will be more changes but not yet finalized_
- No need to pass a URL to the `constructor` function of the `Surreal` class anymore. It's optional which allows you to initialize later with the `.connect()` function
- Adding a dependency on the `URL` class broke the library for react-native. Whilst we don't officially support hermes, be dropped this behaviour for a custom URL parser
- Replace `isomorphic-ws` with `unws`. Issues arrised with nextjs server components importing the `isomorphic-ws` package, which has some fundamental problems and is not maintained.
- The output handler did not properly handle an empty response when querying a non-existent key. Now returns `undefined`.
=> Bump v0.7.2

compile.ts
Old version of `unws` is causing issues for people working in a commonjs workspace. [This PR for `unws`](https://github.com/sxzz/unws/pull/5) fixes that issue.
=> Update unws library

src/library/SurrealHTTP.ts, src/strategies/http.ts, src/strategies/websocket.ts, src/types.ts, test/e2e/shared.js
- **Breaking**: The `.use()` function now accepts an object as an argument (`{ ns, db }`).
- You can now pass an `auth` property to the second argument of the constructor and connect functions. This can be a token string or an object you would pass to the `.signin()` function.
- You can now pass a pair of `{ ns, db }` to the constructor and connect functions.
- The auth state and ns/db combo will now be remembered after a possible websocket disconnect and will automatically be restored.
=> Remember auth across possible disconnects

src/library/SurrealSocket.ts, src/strategies/websocket.ts, src/types.ts
Start a live query
```typescript
const uuid = await surreal.live<{
id: string;
prop: number;
}>("query...", (data) => {
if (data.action === 'CLOSE") return;
console.log(data.result);
});
```
Register another listener for an LQ
```typescript
await surreal.listenLive<{
id: string;
prop: number;
}>("uuid...", (data) => {
if (data.action === 'CLOSE") return;
console.log("Second listener! ", data.result);
});
```
Kill a LQ
```typescript
await surreal.kill("uuid...");
```
```typescript
type close = {
action: "CLOSE",
detail: "SOCKET_CLOSED" | "QUERY_KILLED"
};
type create = {
action: "CREATE";
result: Record<string, unknown>;  // Generic type that was passed, always extends default type
};
type update = {
action: "UPDATE";
result: Record<string, unknown>;  // Generic type that was passed, …
```
=> Live Queries implementation

src/strategies/websocket.ts, src/types.ts
Just recently discovered what the `info` method on the websocket protocol actually does
This PR implements the `.info<T>()` method. The info method will essentially execute the following query: `SELECT * FROM $auth`.
Ensure that tests still pass
No
=> Implement info method for WS strategy

src/strategies/websocket.ts
The `.info()` method currently does not await the ready state of the database, whilst it should.
This PR ensures that the `.info()` method will await the ready state.
Ensure that tests still pass
Not directly
=> `.info()` should await ready state

src/library/SurrealHTTP.ts, src/library/isNil.ts, src/library/processAuthVars.ts, src/strategies/http.ts, src/strategies/websocket.ts, src/types.ts, test/e2e/scripts/docker-restart.sh, test/e2e/scripts/run-e2e.sh, test/e2e/shared.js
See #133 for more details. Furthermore, this PR is a continuation of #141.
This PR makes the passing of the `NS` and `DB` properties optional for scope authentication as we already store them in the class. It also adds a test for scope authentication which specifically does not use the `NS` or `DB` properties, and some improvements to the shell scripts.
Added a test which tests this new behaviour
See #133
=> Don't require NS/DB for scope authentication

src/library/SurrealHTTP.ts, src/strategies/http.ts, test/e2e/shared.js
The http `/sql` not accepting variables was a misconception.
This PR implements support for variables alongside a query for the HTTP strategy's `.query()` method.
Update test to also validate that the vars parameter works for both WS and HTTP strategies.
N/A
=> Allow vars in HTTP query method

src/library/SurrealSocket.ts, src/strategies/websocket.ts, src/types.ts
The insert method was implemented in the websocket protocol to allow for batch inserting of data.
This pull request implements the `.insert()` method for the websocket strategy.
To be implemented in a separate PR.
N/A
=> Implement `.insert()` method

src/strategies/websocket.ts, src/types.ts
The websocket protocol introduced a new option to return changes in the form of patches instead of complete records.
This pull request implements the option to enable these patches.
Will be done in a separate PR, live queries are not yet ready
N/A
=> Implement `.live()` diff option

.github/ISSUE_TEMPLATE/config.yml
The discussions link currently links to a non-existing page
It corrects the faulty link
N/A
N/A
=> Fix discussions link

test/e2e/shared.js
The `.insert()` method is currently not being tested
It adds tests for the `.insert()` method.
- Add a test to insert a single record
- Add a test to test bulk insert of records
Not directly, but the `.insert()` method is currently not being test which is an issue.
=> Add test for `.insert()`

.github/workflows/test.yml, README.md, src/library/SurrealSocket.ts, src/strategies/http.ts, src/strategies/websocket.ts, src/types.ts, test/e2e/bun.js, test/e2e/deno.js, test/e2e/node.js, test/e2e/scripts/run-e2e.sh
- Promises were slightly weirdly handled and opened way to early when they were not yet used.
- Errors caused by the .connect() method that the constructor method invokes are impossible to be caught, as the constructor method in JavaScript classes cannot by async. We are dropping support for passing a URL and connection options directly to the class's constructor method for that reason.
- The authenticate method should return a success state
It addresses the above items. Unfortunately, deno (with --trace-ops) still still reports a dangling promise, however every promise is now either rejected or resolved. This might be a generic error, I will investigate further soon to properly nail …
=> Improvements to promises + error handling. Drop support for URL on constructor method

project.json, src/strategies/http.ts
Query variables are not working when using HTTP strategy. This change unblocks being able to use HTTP strategy in next-auth (https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-surrealdb/tests/rest.test.ts).
Stringifies all types of variables, not only objects.
Without the change, this doesn't work as expected (i.e. with the socket strategy).
```typescript
const sessions = await surreal.query<[SessionDoc<UserDoc>[]]>(
`SELECT *
FROM session
WHERE sessionToken = $sessionToken
FETCH userId`,
{ sessionToken }
)
```
This works, but is not how it's supposed to:
```typescript
const sessions = await surreal.query<[SessionDoc<UserDoc>[]]>(
`SELECT *
FROM session
WHERE sessionToken = $sessionToken
FETCH userId`,
{ sessionToken: `"${sessionToken}"` } // or …
```
=> fix: stringify all variables

src/library/SurrealSocket.ts
#172 
Websocket errors are now always forwarded, no matter the error type. This also fixes #172 
N/A
fixes #172
=> Always forward rejection, no matter the error type

test/e2e/shared.js
See #180
It changes the tests so that `.authenticate()` method is tested for both scope and root users
See above
invalidates #180
=> Change tests so that `.authenticate()` is tested for both scope and root users

src/library/SurrealSocket.ts, src/strategies/websocket.ts, src/types.ts
There was no way to listen for connection closure.
This PR allows you to pass the `onConnect`, `onClose` and `onError` methods to the constructor of the `Surreal` class. These hooks will be reused across all socket connections.
Ensure tests still pass
No
=> Status hooks

src/index.ts, src/library/PreparedQuery.ts, src/library/tagged-template.ts, src/strategies/http.ts, src/strategies/websocket.ts, src/types.ts, test/e2e/bun.js, test/e2e/deno.js, test/e2e/node.js, test/e2e/shared.js
See #185 
- It exposes a `PreparedQuery` class which can be passed to the `.query()` and `.query_raw()` methods.
- It exposes a `surrealql` (and `surql` as a shortcut) function which can be used as a tagged template literal
```js
const name = "John Doe";
const age = 44;
// With PreparedQuery
const query = new PreparedQuery(
/* surql */`RETURN $name; RETURN $age`,
{ name, age }
);
const prepared = await db.query(query);
// With a tagged template literal
const templated = await db.query(
surrealql`RETURN ${name}; RETURN ${age}`
);
```
Added tests to test both
Fixes #185
=> Tagged template literals

src/library/orm/builder/select.ts
Obvious possibility of having the query fail
Fixes the `limit` parameter check that erroneously looks at `start`
obviously passing start parameter will also trigger limit which can be undefined
not seen
=> select.ts limit,start fix

src/strategies/websocket.ts
Currently, errors that occur within `SurrealSocket.send()` are not surfaced properly, making them uncatchable. This leads to issues such as crashing a user's program if an error occurs, without letting them re-establish the database connection or continue execution gracefully.
This PR catches any inner errors, upon which the outer `send()` promise is rejected with the subsequent error. This allows for the error to be surfaced and caught.
I tested this change by running an infinite loop that would try to insert data into a running in-memory SurrealDB instance. The insert statement was surrounded by a try/catch block which would break the loop upon catching any errors and print a console.log message. While the loop was running, I would stop the SurrealDB instance and observe the results in …
=> fix: reject send promise upon catching inner error

src/library/tagged-template.ts
Currently, calling `surrealql` as a tagged function gives a TypeScript error complaining about the argument type of 'TemplateStringsArray` not being assignable to the parameter type of 'string[]'
This change adds 'TemplateStringsArray' as a valid argument type to the `surrealql` function. It does not remove 'string[]' as a valid argument, and thus should not be breaking for any existing usage of the function. As `surrealql` does not make use of any properties specific to either 'TemplateStringsArray' or 'string[]', there should be no conflict in allowing both argument types.
I imported the package from the change branch in a test project and observed that the error no longer was shown when calling `surrealql` as a tagged function. I also checked that the function still accepted an …
=> fix: allow TemplateStringsArray as argument to `surrealql()`

src/surreal.ts, src/types.ts
We were sending too many fields on auth vars, causing signin to silently fail. Additionally, we were checking for a `detail` field for errors, while it was simply `result`
Fixes above
=> Fix sending too many fields on auth vars

src/library/cbor/geometry.ts
When I was reading the code I noticed a few forgotten types that were checked with `instanceof` inside the constructor.
Make sure it accepts the missing type as an argument.
Before the change when you instantiated a new GeometryCollection with the given argument of another GeometryCollection instance that already exists. The error that typescript gives is:
`Argument of type 'GeometryCollection' is not assignable to parameter of type '[Geometry, ...Geometry[]]'`
After the change the argument accepts a other GeometryCollection class.
The following classes had the same forgotten type issue:
- GeometryMultiLine
- GeometryMultiPolygon
- GeometryCollection 
There are no related issues.
=> fix: forgot type in constructor for some geometry classes

src/surreal.ts
The type that would be generated for the `.info()` method was faulty.
We now manually set the type for `.info()`, causing it not be broken.
Ensure all tests still pass
N/A
=> Fix broken .info() type

src/surreal.ts, src/types.ts, tests/integration/mod.ts, tests/integration/tests/live.ts
Thank you for the great work on this project.
I was unable to subscribe to record changes using the live method. After researching, I found the following:
- Live query ID is verified by `z.string().uuid()`.
- In actuality, it is decoded as the UUID class, not a string.
- Make live queries work.
- Changing the string type to UUID prevents users from using it incorrectly.
Add three tests to `tests/integration/tests/live.ts`:
1. The test suite "live" checks that the `live` method returns a UUID class on the WebSocket engine and verifies that live queries work. Also, checks that it fails on the HTTP engine.
2. The test suite "unsubscribe live" checks whether a subscribed live query can be unsubscribed using the UUID class returned by the `live` method. As far as the HTTP engine is concerned, …
=> Fix live query UUID

src/library/engine.ts
Trying to disconnect or reconnect from a failed connection via the WebsocketEngine would throw the error of the previous failed connection. Additionally, because `ready` and `status` props were optional on the abstract `Engine` class, they were not implemented everywhere.
The `.disconnect()` method now suppresses any thrown errors from the previous ready state and simply discards the socket and ready state.
Ensure tests pass
N/A
=> Improve status handling

src/surreal.ts
You can currently not connect to a SurrealDB database running behind a proxy on a sub path
Instead of forcing the path to `/rpc`, `/rpc` will be appended if missing
=> Allow connecting to subpaths

src/library/engine.ts
Thank you for the great work on this project.
Recently, CI has been failing due to WebSocket resource leaks.
Surreal's `close` method waits until the engine it is using transitions to a "disconnected" status. However, the WebSocket engine's `disconnect` method immediately transitions to the "disconnected" status after requesting that the socket be disconnected. The `close` method of socket (not Surreal) only requests that the connection be closed, and certainly does not wait for the connection to close. Therefore, if the socket "close" event occurs before `setStatus` is resolved, there will be no resource leak, but if `setStatus` is resolved first, a resource leak will occur.
In order to detect a WebSocket disconnection, prevent the WebSocket engine from immediately transitioning to the …
=> bugfix: Fix resource leaks in the WebSocket engine

src/errors.ts, src/library/engine.ts
When no namespace and/or database is set a `ConnectionUnavailable` error will be thrown, this can be confusing as it does not clearly represent the problem.
It introduces a new `MissingNamespaceDatabase` error with a better description of what the problem is.
N/A
fixes #245
=> Explicit error when namespace and/or database are missing for HTTP engine

compile.ts, deno.json, deno.lock, src/errors.ts, src/index.ts, src/library/engine.ts, src/library/versionCheck.ts, src/surreal.ts, src/types.ts, tests/unit/isVersionSupported.ts
Especially now, where the minimum required version for the library is 1.4.2, it's very useful to implement a version check to ensure people are on the correct version.
It implements a version check.
Added a test for the version checking logic. Besides that, tests integration tests will fail if the remote version is not supported.
Fixes #84
=> Implement version check

src/surreal.ts, tests/integration/tests/querying.ts
SurrealDB 1.5.0 introduces new `run` and `relate` methods to the RPC protocol.
It implements the new `run` and `relate` methods.
Added a test for both `run` and `relate`
N/A
=> Add `run` and `relate` method

.npmrc, compile.ts
Due to the usage of `fetch`, the minimum version of NodeJS for surrealdb.js is 18.0.0
It sets the engines minimum version for NodeJS
N/A
N/A
=> Require Node v18

src/library/cbor/geometry.ts
Our initial understanding of `Line` was that it's a Line, which is represented by two Points. SurrealDB's Line is actually a LineString however under the hood, which is represented by two _or more_ Points. The types for that are currently incorrect, as pointed out in #263.
It corrects the types.
N/A
Fixes #263
=> A Line is actually a LineString, which accepts two or more Points

src/library/engine.ts, src/library/versionCheck.ts, src/surreal.ts, src/types.ts, tests/integration/env.ts, tests/integration/surreal.ts, tests/integration/tests/connection.ts
Version check would take a long time to complete if the server was unreachable, due to default fetch timeouts in runtimes.
It adds a `versionCheckTimeout` option to the `.connect({ .. })` method, with a default value of 5000ms.
N/A
N/A
=> Version check timeout

src/library/cbor/geometry.ts, tests/unit/__snapshots__/jsonify.ts.snap
Fix `GeometryCollection` class as it takes/returns a `geometries` prop instead of a `coordinates` props.
=> fix: fix GeometryCollection class

src/library/cbor/geometry.ts
Missing this type in a previous change. `GeometryPolygon` can have 1 exterior ring, then >= 0 exterior rings.
=> fix: update GeometryPolygon type

src/library/cbor/index.ts, tests/integration/tests/querying.ts
Add missing table cbor decoding.
Add a new integration test
Fixes https://github.com/surrealdb/surrealist/issues/287
=> Add missing table cbor decoding

compile.ts, src/library/engine.ts, src/surreal.ts, tests/integration/tests/querying.ts
The close method does not work nicely with embedded databases, because the wasm library does not emit disconnect events onto the event emitter. The engine should handle closing the connection instead
The engine now awaits the disconnected message and will resolve the promise
CI
Yes, though no issue on GitHub was previously created.
=> Engine should handle closing the connection

src/library/cbor/geometry.ts
I guess it was there for a reason.
Revert change on `geometries` property to properly handle JSON serialization.
N/A
Tested with Surrealist. The inner geometries are not converted into JSON objects.
=> fix: fix json conversion of geometries

src/library/cbor/recordid.ts, tests/unit/__snapshots__/jsonify.ts.snap, tests/unit/jsonify.ts
#281 
When the ident is a string, we will check if it can be parsed as an integer. If that is the case, it will be escaped
Added a test
Fixes #281
=> number-looking like string should be escaped

src/surreal.ts, tests/integration/tests/querying.test.ts
an `upsert` method was introduced in the CBOR protocol
Adds `upsert`
Added test
Fixes #285
=> Add upsert

src/cbor/decoder.ts, src/cbor/encoder.ts, src/cbor/partial.ts, src/surreal.ts, src/util/PreparedQuery.ts, tests/integration/tests/querying.test.ts
In an oversight, `PreparedQuery` used just a bare minimal CBOR encoder, leaving custom tags such as record ids not properly encoded.
Alters the `partiallyEncodeObject` method to accept all encode options, allowing the `PreparedQuery` class to pass a replacer to the CBOR encode method.
Added a test to ensure that prepared queries have replacer context.
No
=> Ensure PreparedQuery has replacer context

scripts/build.ts
Minifying identifiers make them difficult to read in for example browsers when logging classes.
Changes minification to only affect syntax and whitespace, excluding identifiers
GitHub CI
No
=> Do not minify identifiers

package.json, scripts/build.ts
Because the cjs output did not have a cjs extension, it could not be required as such.
It changes all outputted bundled to have either a cjs or mjs extension
GitHub CI
No.
=> Fix CommonJS target

src/cbor/decoder.ts, src/cbor/encoder.ts, src/cbor/reader.ts, src/cbor/writer.ts
As reported in [Discord](https://discord.com/channels/902568124350599239/1013527402674139268/1260922437479170128), our custom CBOR implementation had some serious performance implications
Made some improvements to the encoder, decoder, writer and reader, making the CBOR implementation even faster than the original library that we used.
GitHub CI. Benchmark tests to be added soon to prevent this sort of performance decline from happening in the future.
No
=> CBOR performance improvements

src/data/types/duration.ts, src/data/types/recordid.ts, src/data/types/table.ts, src/types.ts, tests/unit/convertAuth.test.ts
`convertAuth` threw an error if a namespace was specified, while database was omitted.
It makes `database` optional, and additionally some generic `Error` instances are now converted to `SurrealDbError`
Added a test for `convertAuth`
No
=> Fix errors

src/engines/http.ts, src/engines/ws.ts, src/surreal.ts
Appearantly, the RPC protocol allows you to use only a namespace or database, as long as two values are passed in the argument array. Ommitted values can be represented as none
It allows you to partially use only a namespace
GitHub CI
No
=> Allow partial use

src/data/index.ts
The `escape_ident` method was not properly exported
Fixes the export
GitHub CI
No
=> export `escape_ident`

src/engines/http.ts, src/engines/ws.ts, src/surreal.ts
Allow to unset ns/db
Allow to unset ns/db
GitHub CI
No
=> Allow unsetting ns/db

src/surreal.ts, src/types.ts, src/util/processAuthVars.ts, tests/integration/tests/auth.test.ts, tests/unit/convertAuth.test.ts
With the introduction of `TYPE BEARER` on `DEFINE ACCESS`, it will now be possible to also pass `username` and `password` properties for record access, but with the current implementation these won't be translated. Passing additional variables on the root of the object has never been clean, so we're changing this implementation.
To pass variables to record access, they will now need to be passed via the `variables` property. Nested in there, `ns`, `db` and `ac` cannot be passed, as they are used internally.
Additionally, we added in the `AccessSystemAuth` type.
Updated tests
No
=> Differentate access auth between system and record users

biome.json, src/types.ts
A console.log accidentially snooped into the code during testing.
- Removes the `console.log`
- Enables a linting rule to error upon finding `console.log`
GitHub CI
Fixes https://github.com/surrealdb/surrealdb.js/issues/319
=> No `console.log`

.github/workflows/publish.yml
The recent versions on the `surrealdb` package have been tagged with beta, while latest is 2 years out of date.
For now published to latest
GitHub Actions
=> Publish to latest for now

src/engines/http.ts, src/errors.ts, tests/integration/surreal.ts, tests/integration/tests/connection.test.ts
Currently HTTP based RPC messages such as `signin` and `version` are disallowed from executing unless a namespace and database is defined, which is not necessary.
Improved the HTTP RPC validation logic to allow a manually defined list of RPC methods when no namespace or database is defined.
Added tests
- #303
=> Improve rpc method validation

package.json, src/index.ts, src/surreal.ts, src/util/string-prefixes.ts, tests/unit/string-prefixes.test.ts
With SurrealDB 2.0.0 launched, we're now ready to stabilize the 1.0.0 release of the SurrealDB JavaScript SDK!
Bumps version to 1.0.0, and fixes a couple last typescript issues. Additionally adds a missing RPC method.
GitHub CI
No
=> Stabilize 1.0.0

src/index.ts
Improved typing in WASM and Node SDKs
Exposes the `Engines` type, which we consider to be the recommended way to register additional engines
N/A
=> Expose engines type

src/data/types/decimal.ts, src/data/types/duration.ts, src/data/types/future.ts, src/data/types/geometry.ts, src/data/types/range.ts, src/data/types/recordid.ts, src/data/types/table.ts, src/data/types/uuid.ts, src/data/value.ts, src/index.ts, src/util/equals.ts, tests/unit/__helpers.ts, tests/unit/equals.test.ts, tests/unit/jsonify.test.ts
There is currently no convenient way to compare SurrealQL values, such as UUIDs or record ids.
Adds a new `equals` function to each SurrealQL value type, as well as an exported `equals` function which performs deep equality on two values.
Added a unit test
=> Value deep equality function

src/util/prepared-query.ts, src/util/tagged-template.ts, tests/integration/tests/querying.test.ts
For every run of the tagged-template method, we can re-use a binding for gaps, so that the value will be transferred just once.
Updated the logic to re-use bindings where possible.
Added a test.
- No
=> Reusable gaps

src/data/types/recordid.ts
PR #372.
Checks if the provided argument is already an instance of a StringRecordId.
There is not already a test file for StringRecordId. My code change adds 2 lines and it's simple enough to know it's not going to implode.
#372
=> Add toleration for StringRecordId (#372)

src/data/types/recordid.ts
Having support for initializing StringRecordId in cases where the input may already be a RecordId or a StringRecordId and not just a plain string.
Adds support for initialing a `StringRecordId` object with a provided `RecordId` object.
This class doesn't have any tests yet, and my changes were trivial.
#372 #373
=> Add support for RecordId (#372)

src/engines/abstract.ts, src/engines/http.ts, src/engines/ws.ts, src/errors.ts, src/types.ts
The upcoming 2.1.0 release of surrealdb will add support for configurable exports
Adds a `.export()` method
GitHub CI
N/A
=> Add `.export()`

src/data/cbor.ts, src/data/index.ts, src/data/types/decimal.ts, src/data/types/duration.ts, src/data/types/future.ts, src/data/types/geometry.ts, src/data/types/range.ts, src/data/types/recordid.ts, src/data/types/table.ts, src/data/types/uuid.ts, src/data/value.ts, src/index.ts, src/surreal.ts, src/util/emitter.ts, src/util/equals.ts, src/util/escape.ts, src/util/jsonify.ts, src/util/prepared-query.ts, src/util/string-prefixes.ts, src/util/tagged-template.ts, src/util/to-surrealql-string.ts, src/util/version-check.ts
Some functions and classes are undocumented, inconsistent, or unclear
- Add documentation to most of the public facing API
- Moved ident escaping functions to a dedicated util file
- Renamed functions to adhere to JavaScript conventions
- Previous names are still available, albeit marked as deprecated
CI
=> Clean up the public API

src/util/escape.ts, tests/unit/idents.test.ts
Empty string idents currently are not escaped, which is invalid SurrealQL
Empty strings will always be escaped
Unit tests
=> Fix empty ident escaping

src/engines/abstract.ts, src/engines/http.ts, src/engines/ws.ts, src/surreal.ts, tests/integration/tests/__snapshots__/import.test.ts.snap, tests/integration/tests/import.test.ts
Unlike `export`, there is not currently a dedicated `import` function
Exposes an `import` function which executes a POST `/import` request, and can also be implemented separately for surrealdb.wasm
Unit test
=> Expose import function

src/util/emitter.ts, tests/unit/emitter.test.ts
See #395
It fixes two issues in the emitter's unsubscribe logic:
- If the index of the listener in it's group was `0`, the check if we found an index would fail, causing the listener not to be removed.
- If the group for a certain event was empty, it would not be cleared out.
Added a test
- Fixes #395
=> Fix emitter leak

.github/workflows/ci.yml, README.md, package.json, src/data/cbor.ts, src/data/types/range.ts, tests/integration/tests/querying.test.ts
Decoding ranges was broken, because inner bounds are decoded at an earlier stage
Fixes decoding of bounds.
Tests which tested bounds are now no longer marked as todo.
Not that I'm aware
=> Fix range value decoding

src/auth.ts, src/engines/abstract.ts, src/engines/http.ts, src/engines/ws.ts, tests/integration/surreal.ts, tests/integration/tests/connection.test.ts
Authentication calls in `prepare` currently lock the underlying engine
Change the order of operations and abstract the force flag to allow RPC invocations during prepare
Added an auth prepare test
No
=> Prevent prepare from locking

.github/workflows/ci.yml, tests/integration/surreal.ts, tests/integration/tests/connection.test.ts, tests/integration/tests/live.test.ts
The spawn and kill currently rely on timeouts.
They now rely on stdout and actual promises. Also, this PR introduces an `SURREAL_VERSION_CHECK` envvar in the test suite which disables the version check when set to false. To be used in the surrealdb repo
GitHub CI
N/A
=> Improve tests spawn and kill

packages/node/src-ts/engine.ts, packages/sdk/src/cbor/codec.ts, packages/sdk/src/cbor/index.ts, packages/sdk/src/cbor/utils.ts, packages/sdk/src/engine/http.ts, packages/sdk/src/engine/websocket.ts, packages/sdk/src/flatbuffer/codec.ts, packages/sdk/src/internal/http.ts, packages/sdk/src/surreal.ts, packages/sdk/src/types/surreal.ts, packages/wasm/src-ts/engine.ts
The encoding and decoding flow of the SDK is currently too rigid to allow customisation and certain advanced use cases.
This PR implements a value codec system in order to allow users to configure the behaviour of the encoders/decoders, as well as implement their own. 
CI
This is a future proof alternative to #387
=> Implement codec system

packages/sdk/src/controller/index.ts, packages/sdk/src/errors.ts, packages/sdk/src/surreal.ts, packages/sdk/src/utils/publisher.ts, packages/tests/integration/connection.test.ts
It may be desirable in tooling and other advanced contexts to subscribe to namespace or database changes.
This PR introduces a `using` event on the Surreal class which is called each time a namespace or database is selected, including on connect. Additionally, it is also called when `reset` is invoked.
This PR also improves error handling of event publishers in order to combine subscriber errors together.
Added test
=> Add "using" event

packages/tests/integration/__snapshots__/export.test.ts.snap, packages/tests/integration/export.test.ts, packages/tests/integration/query/query.test.ts
The SDK tests that run in SurrealDB have been failing ever since we began the 3.x changes.
This change attempts to fixup the tests so they work when run against 3.0.
Ran against 3.0 locally:
```
$ SURREAL_EXECUTABLE_PATH=/Users/stu/dev/worktrees/surrealdb.wt2/target/debug/surreal bun test
bun test v1.2.9 (9a329c04)
packages/tests/unit/cbor.test.ts:
✓ cbor > infinity > valid bytes [0.85ms]
✓ cbor > infinity > invalid bytes, nested infinite bytes [0.73ms]
✓ cbor > infinity > invalid bytes, no break [0.04ms]
✓ cbor > infinity > invalid bytes, invalid major [0.02ms]
✓ cbor > infinity > valid text [0.04ms]
✓ cbor > infinity > valid array [0.04ms]
✓ cbor > infinity > valid map [0.01ms]
✓ …
```
=> Fix JS SDK tests for SurrealDB 3.0
