package.json
rollup.config.ts

creates a single file in `./dist/web/index.js`
closes #16

add browser cdn build

---

.github/workflows/lint.yml
deno.json
mod.ts
rollup.config.ts
src/classes/emitter.ts
src/classes/live.ts
src/classes/pinger.ts
src/classes/socket.ts
src/errors/index.ts
src/index.ts
src/utils/guid.ts

I use the same config (+ tests) for own project.

feat: add linter + formater as github action

---

src/classes/pinger.ts

This is a type where Node, Browser, Deno have different types so set it here to any.

fix: pinger type

---

src/index.ts

Co-authored-by: @michaelprichardson

feat: add doc comments from #5 (but without types)

---

mod.ts

This fixes the currently broken /mod.ts...

deno: add default to export in /mod.ts

---

.github/workflows/publish.yml

closes #37 
TODO (for @tobiemh):
Add an env var to this repo named `NPM_TOKEN` with a auth token (see https://docs.npmjs.com/creating-and-viewing-access-tokens)
(Ready for review / merge)

workflow: add auto publish

---

src/index.ts

I'm not sure if this modification is necessarily correct, but I hope it can be useful for something.
- https://github.com/surrealdb/surrealdb.js/issues/68

Use Surreal.wait() method to ensure connection to database

---

README.md

docs: add getting started + updated contribution guide

---

.github/workflows/publish.yml
project.json

The wrong build command was used which caused the web bundle not to be built

Fix/web build 0.7.1

---

src/errors.ts
src/library/SurrealHTTP.ts
src/library/SurrealSocket.ts
src/library/processUrl.ts
src/strategies/http.ts
src/strategies/websocket.ts

Lose the URL dependency

---

compile.ts

Added the `ws` package as a direct dependency to fix installation with yarn

Fix install with yarn

---

project.json

- **Breaking**: Fix typings for `.select()`, `.create()`, `.update()`, `.merge()`, `.patch()`, `.delete()`
- After this PR, all of the above mentioned functions will always return an array, regardless of the method or if you are selecting a table or a specific record.
- The `.select()` methods now returns an array instead of a single item.
- The `.change()` method is renamed to `.merge()`.
- The `.modify()` method is renamed to `.patch()`.
- The above mentioned functions now always return an array, never a single item or `undefined`.
- **Breaking**: The `.use()` function now accepts an object as an argument `.use({ ns, db })`.
- You can now pass an auth property to the second argument of the constructor and connect functions. This can be a token string or an object you would pass to the …

Bump v0.8.0

---

src/strategies/websocket.ts
src/types.ts

- The type for the `data` argument in the `create`, `update` and `merge` methods is now separated from the function's return types.
- The type for the `data` argument in the `create`, `update` and `merge` methods excludes any `id` property by default, as this is controlled by the thing
- The typing for the `data` property of the `merge` function now makes every property optional by default.
```typescript
type Book = {
id: string;
name: string;
author: string;
updated: Date;
};
// We need a custom ID and the updated field is controlled by the SurrealDB schema...
type CreateBook = Exclude<Book, 'id' | 'updated'>;
// Returned type is still "Book", but the type used for the data argument is "CreateBook".
await surreal.create<Book, CreateBook>('book', { 
name: 'Surrealdb.js For Dummies', …
```

Separate data type from resulting type

---

.github/CODEOWNERS
.github/FEATURE_TEMPLATE/bug_report.yml
.github/FEATURE_TEMPLATE/config.yml
.github/FEATURE_TEMPLATE/documentation.yml
.github/FEATURE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md

Replicated from the main [SurrealDB repository](https://github.com/surrealdb/surrealdb/blob/main/.github)

Github Issue/PR templates; Codeowners

---

project.json

Bump version for patch release
Bumps version for patch release
Ensure tests still pass
No

Bump v0.8.1

---

project.json

Bump v0.8.2

---

project.json

Release a new patch version
Bumps the patch number 
N/A
N/A

Bump v0.8.3

---

src/library/SurrealSocket.ts

Some debugging leftovers were merged into main by accident
It removes the debugging leftovers
N/A
N/A

Remove debugging leftovers

---

.github/workflows/test.yml
src/library/SurrealSocket.ts
src/strategies/websocket.ts
src/types.ts
test/e2e/scripts/docker-restart.sh
test/e2e/shared.js

There were some open issues surrounding live queries which needed to be tackled
- Rename `query` to `table` for `.live()` method
- Update implementation to reflect chosen messaging format
- Make docker use nightly image to test live queries
- Add tests for live queries
Added tests for live queries
No, well, live queries were still not functional up until now :)

Finish up live queries implementation

---

project.json

To do a patch release
Bumps the package's version to v0.8.4
Ensure that all tests pass
No

Bump v0.8.4

---

project.json

New release
Bumps version
N/A
No

Bump v0.9.0

---

test/e2e/shared.js

#171 changed the behaviour of how variables for the `.query()` method are being encoded.
This PR validates the above change
Added a test that sends over various types of variables.
N/A

Test that query variables are properly encoded

---

project.json

new release
Bumps version 
N/A
N/A

Bump v0.9.1

---

src/types.ts

See #178
Adds `boolean` to `RawQueryResult` type.
N/A
Fixes #178

Add `boolean` to `RawQueryResult`

---

project.json

New release
Bumps version to v0.10.0
N/A
N/A

Bump v0.10.0

---

project.json

Bump for release
Bumps package version
N/A
N/A

Bump v0.10.1

---

README.md

Since you recently changed ns to namespace and db to database, I thought in update this readme
Change the readme to be up to date
I did not because the link is broken

Update README.md to address namespace and database naming changes

---

test/e2e/shared.js

See #180, wanted to test explicitely namespace and database authentication
Implements tests for scope signup, namespace signin and database signin
Ensure added and updated tests pass
See #180

Improved auth tests

---

project.json

New release 
Bumps version
N/A
N/A

Bump v0.11.0

---

compile.ts
test/e2e/shared.js

The response checked against the live responses is incorrect
Fixes the test
Ensure tests pass
Unblocking #220

Fix live test

---

project.json

Bump v0.11.1

---

project.json

Bump v1.0.0-beta.1

---

project.json

Bump v1.0.0-beta.2

---

src/index.ts
src/library/cbor/geometry.ts
src/library/emitter.ts

Some types needed to write new engines were not exported
They are now exported
Ensure all tests still pass
N/A

Export more types

---

project.json

Bump v1.0.0-beta.3

---

project.json

Bump v1.0.0-beta.4

---

project.json

Bump version to v1.0.0-beta.5

---

src/surreal.ts
tests/integration/mod.ts
tests/integration/tests/connection.ts
tests/integration/tests/querying.ts

Query the remote database version over RPC allowing for custom version checking
Exposes a new `version` method on Surreal instances
Added unit test

Add version method

---

project.json

Bump version
Bump version
N/A
N/A

Bump version to v1.0.0-beta.6

---

project.json

Bump version
Bump version
N/A
N/A

Bump version to v1.0.0-beta.7

---

project.json

Bump version
Bump version
N/A
N/A

Bump version to 1.0.0-beta.8

---

.github/workflows/ci.yml
src/library/cbor/geometry.ts

* fix current lint issue
* enforce ci pipeline for PRs

chore: fix lint issue

---

project.json

New release
Bumps version
GitHub CI
N/A

Bump version to v1.0.0-beta.9

---

package.json

New release
Bumps version
GitHub CI
No.

Bump version to v1.0.0-beta.11

---

package.json

New release
Bumps version
GitHub CI
No

Bump version to 1.0.0-beta.13

---

package.json

New release
Bumps version
GitHub CI
No

Bump version to 1.0.0-beta.14

---

package.json

New release
Bumps version
GitHub CI
No

Bump version to 1.0.0-beta.15

---

package.json

New release
Bumps version
GitHub CI
No

Bump version to 1.0.0-beta.16

---

package.json

New release
Bumps version
GitHub CI
No

Bump version to 1.0.0-beta.17

---

package.json
src/engines/http.ts
src/engines/ws.ts
src/surreal.ts

Bump version and fix issue
Bumps version and fixes issue
GitHub CI
No

Bump version to 1.0.0-beta.18

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
README.md
package.json

We are renaming the `surrealdb.js` NPM package to `surrealdb`
Renames `surrealdb.js` to `surrealdb`
GitHub CI
No

Rename `surrealdb.js` to `surrealdb`

---

package.json

New release
Bumps version
GitHub CI
No

Bump version to 1.0.0-beta.19

---

package.json

New release
Bump version
GitHub CI
N/A

Bump version to 1.0.0-beta.21

---

.github/workflows/ci.yml
.github/workflows/publish.yml
package.json
src/data/types/recordid.ts

In the last publish, there was an issue by JSR
This PR, besides bumping the version, introduces a dry-run publish, and ensures that the publish workflow depends on CI.
See above.
N/A

Bump version to v1.0.2

---

.github/workflows/ci.yml
.github/workflows/publish.yml
package.json

There was an issue in CI causing the stable version to be released under a beta tag
Fixes CI momentarily
GitHub CI
N/A

Bump version to v1.0.3

---

package.json

New release
Bumps version
GitHub CI
N/A

Bump version to 1.0.5

---

package.json

Adds a proper description and some keywords to package.json
GitHub CI
N/A

Add description and keywords

---

src/data/types/future.ts

Removed incorrect future block wrapping
Yeet braces
CI
https://github.com/surrealdb/surrealdb/pull/5050

Fix future toString

---

src/engines/ws.ts

See #361
Fixes websocket connections for cloudflare workers
GitHub CI
Fixes #361

Cloudflare Worker fixes

---

scripts/build.ts

See #370
Adds back sourcemaps
GitHub CI
Fixes #370

Add back sourcemaps

---

package.json

bump version to 1.1.0

---

tests/integration/env.ts
tests/integration/surreal.ts

Make test executable configurable

---

package.json

New pathc
Bumps version
GitHub CI
N/A

Bump version to 1.3.2

---

.github/workflows/check.yml
.github/workflows/publish.yml
package.json
packages/cbor/package.json
packages/sdk/package.json
scripts/publish/publish.ts

Update CI and bump version

---

.github/workflows/publish.yml

Fix invalid dependency

---

bun.lock
package.json
packages/cbor/package.json
packages/sdk/package.json
packages/tests/integration/query/live.test.ts

Bun does not update the lockfile due to an issue
Manually update lockfile and bump version

Fix lockfile not updating

---

packages/sdk/src/engine/websocket.ts

Blob.bytes() isn't available on Chrome-based browsers so connection was failing silently.
Moreover, we can drop the Blob codepath and default to arraybuffer, which is more efficient and eliminates the async callback completely.

Fix WebSocket engine on Chrome (#433)

---

README.md

Fix typo and clarify node engine

---

demo/node/demo.ts
packages/node/Cargo.lock
packages/node/package.json
packages/node/src-rust/app/mod.rs
packages/node/src-ts/engine.ts
packages/wasm/Cargo.lock
packages/wasm/package.json
packages/wasm/src-rust/app/mod.rs
packages/wasm/src-ts/engine.ts
scripts/sync-surreal.ts

- WASM and Node engines threw an error when connecting concurrently
- Node did not yet support live select
- Fix WASM and Node engines and avoid concurrent connections
- Implement support for live select in the Node engine
- Update surrealdb
CI + Demo

Update embedded engines
